### ISSUE TITLE
FID-infinite comparison and discussion

### ISSUE THREAD

**Issue by ogencoglu** [clovaai/generative-evaluation-prdc#1]
Thanks for the interesting work!

This is not an issue regarding your source code but just a comment to your study. 

I believe it would be fair to discuss and cite the recent work by Min Jin Chong and David Forsyth [Effectively Unbiased FID and Inception Score and where to find them
](https://arxiv.org/abs/1911.07023) where they propose unbiased drop-in replacements for FID scores.

**Comment by coallaoh** [comment]
Thank you too for the interest in our work :)
And thanks for pointing out the interesting work. We are indeed aware of the paper, but have not managed to include a discussion in the first version of our paper.

Please note that our claim is not to _replace_ FID and Inception scores with our density and coverage metrics. They serve different purposes. FID and Inception scores provide single-value assessments that are useful for ranking generative models by their performances. On the other hand, density and coverage are fidelity-diversity metrics (as are precision and recall metrics) that serve more diagnostic purposes. Our argument is that for fidelity-diversity metrics, density and coverage are better than precision and recall metrics. We believe it makes a lot of sense to use our density and coverage metrics together with the unbiased FID or IS in the future.

We will include this discussion in the next version :)

**Comment by ogencoglu** [comment]
Thank you for the timely and informative response Seong!
