### ISSUE TITLE
Normalize or not normalize?

### ISSUE THREAD

**Issue by ai23resch04001** [clovaai/generative-evaluation-prdc#12]
Hi,
   I am trying to analyze the coverage of some synthetic datasets. I am getting very different PRDC numbers in cases of normalizing the input image before calculating the embeddings vs passing the input image as it is for the calculation of embedding. Could you please suggest which is the correct approach? 

Thank you.

**Comment by jaejun-yoo** [comment]
Hi, you should follow the same setup used during the training of the embedding network. Consistency between the preprocessing steps (e.g., normalization) and the network’s training configuration is crucial for accurate evaluation. If the embedding network was trained with normalized inputs, providing normalized images ensures that the embeddings are extracted correctly and align with the learned representations. Deviating from this setup may lead to embeddings that do not reflect the network’s intended functionality.

**Comment by ai23resch04001** [comment]
Hi, Thanks a lot for your response. that clarifies my query.
