### ISSUE TITLE
How do I use my own image dataset to run your code?

### ISSUE THREAD

**Issue by zxsitu** [clovaai/generative-evaluation-prdc#6]
Hello, your research is very significant to my work.
What I want to ask is, how do I go about running this code to test my images? I have already prepared the original image and the generated image, but I am not quite sure how to run your code program? Can you tell me how to run the code when using my own image dataset?

Is it like this?
run  `prdc . /generate-images ./real-images`
or `compute_prdc . /generate-images . /real-images`

**Comment by mountains-high** [comment]
@zxsitu were you able to solve it? Could you tell me, please? 
Thank you

**Comment by Mahmood-Hussain** [comment]
Hi I have tried to create it please see here: https://github.com/Mahmood-Hussain/generative-evaluation-prdc
