### ISSUE TITLE
About a specific random embedding extraction method

### ISSUE THREAD

**Issue by subinium** [clovaai/generative-evaluation-prdc#8]
When extracting random embeddings, does use a randomly initialized vgg16 mean using an untrained model?

Or does it mean to train and select vgg16 up to a certain threshold as in the deep prior image? If so, how did you set the threshold for that threshold?

May I know the specific code you used or the code you referenced?

**Comment by hellog2n** [comment]
Hi, I think that they used untrained vgg16 which is randomly initialized and the the parameters of the model is fixed in their paper.

I think we can use this code for extracting random embedding from the random init model.
`vgg16 = models.vgg16(pretrained=False)`
